name: Build Multi-Platform Executables

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            executable_name: pyBranchCheck.exe
            artifact_name: pyBranchCheck-windows
          - os: macos-latest
            executable_name: pyBranchCheck
            artifact_name: pyBranchCheck-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # macOS通常已经预装Git
        git --version

    - name: Install system dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Windows通常已经预装Git
        git --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m PyInstaller --onefile --name=pyBranchCheck --add-data="templates;templates" --add-data="config.json;." --hidden-import=flask --hidden-import=webbrowser --hidden-import=threading --hidden-import=subprocess --hidden-import=pathlib --hidden-import=tempfile --hidden-import=shutil --hidden-import=json --hidden-import=datetime --hidden-import=re --hidden-import=time --hidden-import=git app.py --clean

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python -m PyInstaller --onefile --name=pyBranchCheck --add-data="templates:templates" --add-data="config.json:." --hidden-import=flask --hidden-import=webbrowser --hidden-import=threading --hidden-import=subprocess --hidden-import=pathlib --hidden-import=tempfile --hidden-import=shutil --hidden-import=json --hidden-import=datetime --hidden-import=re --hidden-import=time --hidden-import=git app.py --clean

    - name: Test executable
      run: |
        if [ -f "dist/${{ matrix.executable_name }}" ]; then
          echo "✅ Executable created successfully"
          ls -la "dist/${{ matrix.executable_name }}"
        else
          echo "❌ Executable not found"
          exit 1
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable_name }}
        retention-days: 30

    - name: Create Release Assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ matrix.executable_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## pyBranchCheck ${{ github.ref_name }}
          
          ### 下载说明
          - **Windows用户**: 下载 `pyBranchCheck.exe`
          - **Mac用户**: 下载 `pyBranchCheck`，需要在终端中运行 `chmod +x pyBranchCheck` 添加执行权限
          
          ### 使用方法
          1. 确保系统已安装Git
          2. 双击运行程序（Windows）或在终端运行 `./pyBranchCheck`（Mac）
          3. 浏览器会自动打开 http://localhost:5000
          
          ### 重要文件说明
          - **config.json**: 存储仓库配置和平台设置，请勿手动删除
          - **temp_repos/**: 临时仓库文件夹，存储克隆的Git仓库，可以删除以释放空间
          
          ### 更新内容
          - 添加了启动时的用户手册提示
          - 屏蔽了Flask开发服务器警告
          - 优化了配置文件管理
          - 分支关键字支持多个，用英文逗号分隔
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}